
services:

  httpd:
    ports: [ 80:80 ]
    volumes:
     - .:/usr/local/apache2/htdocs

  tailwindcss:
    volumes:
      - .:/project
    command: [ '-i', 'src/source.css', '-o', 'style.css', '--watch', '--poll' ]
    stdin_open: true
    tty: true

  imagick:
    image: dpokidov/imagemagick
    volumes:
      - ./assets:/imgs
    stdin_open: true
    tty: true
    #  docker run -v /your/images:/imgs dpokidov/imagemagick /imgs/sample.png -resize 100x100 /imgs/resized-sample.png
    # entrypoint: [ 'identify' ]
    entrypoint: [ 'convert' ]
